include: package:lint/analysis_options.yaml

linter:
  rules:
    use_setters_to_change_properties: false
    prefer_single_quotes: true  # Uncomment to enable the prefer_single_quotes rule
    unawaited_futures: true
    avoid_positional_boolean_parameters: false
    avoid_function_literals_in_foreach_calls: false
    flutter_style_todos: false
    sort_pub_dependencies: false
    avoid_catches_without_on_clauses: true
    avoid_classes_with_only_static_members: false
    use_build_context_synchronously: false